name: gpodder
version: '3.9.3'
summary: Media aggregator and podcast client
description: |
  gPodder is a simple, open source podcast client written in Python using
  GTK+. In development since 2005 with a proven, mature codebase.

confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  gpodder:
    command: desktop-launch ${SNAP}/bin/gpodder
    plugs: [network, pulseaudio, unity7]

  cli:
    command: gpo
    plugs: [network]

parts:
  mygpoclient:
    plugin: python
    source: https://github.com/gpodder/mygpoclient.git
    prepare: |
      sed -i 's/from distutils.core import setup/from setuptools import setup/' setup.py

  podcastparser:
    plugin: python
    source: https://github.com/gpodder/podcastparser.git
    prepare: |
      sed -i 's/from distutils.core import setup/from setuptools import setup/' setup.py

  gpodder:
    plugin: python
    source: https://github.com/gpodder/gpodder.git
    source-branch: gtk3
    after: [desktop-gtk3, mygpoclient, podcastparser]
    prepare: |
      sed -i 's/from distutils.core import setup/from setuptools import setup/' setup.py
      python3 setup.py sdist
      make messages
      make share/applications/gpodder.desktop
      make share/applications/gpodder-url-handler.desktop
      make share/dbus-1/services/org.gpodder.service
    python-version: python3
    python-packages:
      - mygpoclient
      - podcastparser
    build-packages:
      - help2man
      - intltool
      - make
      - gir1.2-gtk-3.0
      - python3-dbus
      - python3-gi
      - python3-gi-cairo
      - python-gobject-dev
      - python3-html5lib
    stage-packages:
      - gir1.2-gtk-3.0
      - python3-dbus
      - python3-gi
      - python3-gi-cairo
      - python-gobject
      - python3-html5lib

